spring.application.name=sonaerukun
server.port=8081
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://dpg-d732824r85hc73ehg3cg-a.singapore-postgres.render.com:5432/sonaerukun
spring.datasource.username=sonaerukun_user
spring.datasource.password=wX2UDqdQUy7g4Dp7zbe4CD830ELEa6aN
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update